### ISSUE TITLE
question about your wrfout data

### ISSUE THREAD

**Issue by zhyx1991** [AntonGusarov/optimal-interpolation#1]
Hi,
Thanks a lot for your code contribution. I am a beginner in data assimilation and very interested in your work. I would like to test and learn the code, but I found no data about wrfout is available.  Would you please provide a download link to the wrfout data?  If so, I will appreciate it very much.

**Comment by AntonGusarov** [comment]
Hi, 

Thank you very much! I hope it will be useful to you. The WRF data used here was generated by our own proprietary numerical model, so I cannot point you out to this exact data. However, you can search for some reanalysis data for wind. Yes, the grid would be quite sparse but it does not matter for the numerical scheme.

What is more, the code here is uploaded as is from what I found on my computer, there is no guarantee that some minor functionality is not missing. But I guess this is the latest version I used for my paper, and some functions should work as intended.

**Comment by zhyx1991** [comment]
Thanks a lot for your advice.  I will try by using reanalysis data.
